# Generated by Django 3.2.9 on 2021-11-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okta_oauth2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=500)),
                ('user_type', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
